### ISSUE TITLE
[Question] How do you include turbojpeg

### ISSUE THREAD

**Issue by caplett** [jfolz/simplejpeg#1]
Hey, first of all thank you for this package!

Could you give me a hint on how you integrated turbojpeg / libturbojpeg?

I found some reference on the "turbojpeg.h" in the _jpeg.pyx file but i dont see the header.

My current assumption is that you took the some functions out of turbojpeg and compiled them again without other dependencies. But i cant really wrap my head around how exactly.

Best regards!

**Comment by jfolz** [comment]
The build system is a bit complex. pip-installable build dependencies are defined in pyproject.toml. The rest is done by setup.py:

1. Download sources for native dependencies (YASM, libjpeg-turbo)
2. Build YASM
3. Build libjpeg-turbo
4. Build the extension module and statically link libturbojpeg
